<a href="https://colab.research.google.com/github/MAHARAJASINGH/PythonBeginner/blob/master/PythonDay2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
##Array Concepts
thistuple = ("apple", "banana", "cherry")
print(thistuple)
category = ("maths","physics","chem")
print(category)

thistuple = ("apple", "banana", "cherry")
print(thistuple[1])
thistuple = ("apple", "banana", "cherry")
print(thistuple[-1]) 
thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[2:5])
##Immutable dataset
##range from 2 to 4 it will work
##starts with 0 index
thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[-4:-1])

('apple', 'banana', 'cherry')
('maths', 'physics', 'chem')
banana
cherry
('cherry', 'orange', 'kiwi')
('orange', 'kiwi', 'melon')


In [2]:
##List Operation
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2" ,List starts with 0 index
print(xs[-1])     # Negative indices count from the end of the list; prints "2"
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)         # Prints "[3, 1, 'foo']"
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Prints "[3, 1, 'foo', 'bar']"
x = xs.pop()      # Remove and return the last element of the list
print(xs)      # Prints "bar [3, 1, 'foo']"

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
[3, 1, 'foo']


Dictionary Iteration


In [6]:
##Different ways for iteration in Dictionary
#dictionary iteration
d = { 1: 'students', 2: 'working', 3: 'business'}
print('check1') 
##for value at index
print(d[3])
for k in d:
  ##for keys only
  print(k)
print('check2')
##for value in dictinary
for k in d:
  print(d[k])
print('check3')
for v in d.values():
  print(v)
  print('check4')

check1
business
1
2
3
check2
students
working
business
check3
students
check4
working
check4
business
check4


ckeck it pls
height = float(input("Input your height in meters: "))
weight = float(input("Input your weight in kilogram: "))
print("Your body mass index is: ", round(weight / (height * height), 2))
from Sharada Lakshmanan to everyone:
bmi = np_weight / np_height ** 2
from Sumit Singh to everyone:
in_weight=float(input("User input"))

In [7]:
##multiplication of arrays
import numpy as np

x = np.array([[1,2,3],[3,4,5],[6,7,8]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"
print(np.mean(x))
print(np.mean(x,axis=0))
print(np.mean(x,axis=1))

39
[10 13 16]
[ 6 12 21]
4.333333333333333
[3.33333333 4.33333333 5.33333333]
[2. 4. 7.]


try this
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

x = np.array([[1,2,3],
              [3,4,5],
              [6,7,8]])
              

In [8]:
#transpose an array
import numpy as np

x = np.array([[1,2,3,5], [3,4,5,9],[5,6,7,8]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
            ##in Python maintain he in dentation also matters
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

[[1 2 3 5]
 [3 4 5 9]
 [5 6 7 8]]
[[1 3 5]
 [2 4 6]
 [3 5 7]
 [5 9 8]]


In [11]:
##.code in array
##code visible in screen
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([8,10])
w = np.array([11, 10])
print(x)
print (y)
print (v)
print (w)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[ 8 10]
[11 10]


try this
print(v.dot(w))
print(np.dot(v,w))

In [13]:
##dot operators
import numpy as np
x = np.array([[1,2,3],[3,4,5],[6,7,8]])
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"
print(np.mean(x))
print(np.mean(x,axis=0))
print(np.mean(x,axis=1))
 #x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([8,10])
w = np.array([11, 10])
print(x)
print(v.dot(w))
print(np.dot(v,w))
print(x.dot(y))
print(np.dot(x,y))

39
[10 13 16]
[ 6 12 21]
4.333333333333333
[3.33333333 4.33333333 5.33333333]
[2. 4. 7.]
[[1 2 3]
 [3 4 5]
 [6 7 8]]
188
188


ValueError: ignored

In [14]:
##Vector work in python
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(x)
v = np.array([1, 0, 1])
y = x - v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 0  2  2]
 [ 3  5  5]
 [ 6  8  8]
 [ 9 11 11]]


array.shape functionwe use for dynamically knowing the array

In [15]:
import numpy as np 
v = np.array([1,2,3]) # v has shape (3,) 
print(v.shape) 
print(v.reshape(3,1))

(3,)
[[1]
 [2]
 [3]]


In [16]:
# Compute outer product of vectors
#reshape special versions
v = np.array([1,2,3,4,5,6])  # v has shape (3,)
##first one is always colums and second one is rows
print(v.reshape(6,1))
print(v.reshape(3,2))
print(v.reshape(2,3))
##no of elements should be coming in array any how
##all products here are 6 in array

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [19]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(x.shape) ##multiply this always ....array dimension we will get
print(x.reshape(6,1))

(4, 3)


ValueError: ignored

In [21]:
##Transpose and reshape concepts
w = np.array([4,5])    # w has shape (2,)
x = np.array([[1,2,3], [4,5,6]])
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w))
print((x.T + w).T)

[[ 5  9]
 [ 6 10]
 [ 7 11]]
[[ 5  6  7]
 [ 9 10 11]]


In [25]:
##square root of elements
import numpy as np

x1 = np.array([[1,2],[3,4]])
y1 = np.array([[1,2],[3,4]])
print(x1 + y1)

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))
#from 493740 to everyone:
#can you please paste this code also in chat window
#from Sharada Lakshmanan to everyone:
import numpy as np

x1 = np.array([[1,2],[3,4]])
y1 = np.array([[1,2],[3,4]])
print(x1 + y1)

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

##now it is visible

[[2 4]
 [6 8]]
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[2 4]
 [6 8]]
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [26]:
##string operation in python
##string handling done without impoting anything ,,,,directly here
##in algorithmic one we use imports
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


from 568341 to everyone:
yes there are escape sequence \,\t 

In [27]:
sports = ['football','tennis','chess','volley ball','tennis','cricket','basketball','tennis']
print(np.unique(sports))

#np.savetxt('sportsdat.txt',sports,delimiter=',')
#np.savetxt('test.txt',sports,delimiter = ',')
np.save('sample_sport',sports)

['basketball' 'chess' 'cricket' 'football' 'tennis' 'volley ball']


In [28]:
##para example in string with spaces and all
para_str = """this is a long string that is made up of
several lines and non-printable characters such as
TAB ( \t ) and they will show up that way when displayed.
NEWLINEs within the string, whether explicitly given like
this within the brackets [ \n ], or just a NEWLINE within
the variable assignment will also show up.
"""
print(para_str)

this is a long string that is made up of
several lines and non-printable characters such as
TAB ( 	 ) and they will show up that way when displayed.
NEWLINEs within the string, whether explicitly given like
this within the brackets [ 
 ], or just a NEWLINE within
the variable assignment will also show up.



In [29]:
##variables in string
#!/usr/bin/python

print("My name is %s and weight is %d kg!" % ('Zara', 21))

My name is Zara and weight is 21 kg!
