<a href="https://colab.research.google.com/github/MAHARAJASINGH/PythonBeginner/blob/master/PythonDay3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
##input
##variable if condiion boolean
var1 = 100
if var1:
  print("1 - Got a true expression value")
  print(var1)
var2 = 0
if var2: ##I think might be var 2 value is 0 thats why...
   print("2 - Got a true expression value")
   print(var2)
print("Good bye!")

Good bye!


In [2]:
var1 = 10
if var1==100:
   print("1 - Got a true expression value")
   print(var1)
else:
   print("1 - Got a false expression value")
   print(var1)
var2 = 10
if var2==10:
   print("2 - Got a true expression value")
   print(var2)
else:
   print("2 - Got a false expression value")
   print(var2)
print("Good bye!")

1 - Got a false expression value
10
2 - Got a true expression value
10
Good bye!


In [4]:
##input
##if else condition code as well
var = 100
if var == 200:
   print("1 - Got a true expression value")
   print(var)
elif var == 150:
   print("2 - Got a true expression value")
   print(var)
elif var == 100:
   print("3 - Got a true expression value")
   print(var)
else:
   print("4 - Got a false expression value")
   print(var)
print("Good bye!")

3 - Got a true expression value
100
Good bye!


In [21]:
import numpy as np
marks= [70,80,65,68]
print (marks)
avg_marks=np.average(marks)
print (avg_marks)
if avg_marks > 70:
 print("pass")
else:
 print ("Fail")


[70, 80, 65, 68]
70.75
pass


In [12]:
##input
##for break we use
for letter in 'Python':     # First Example
   if letter == 'h':
      break
   print('Current Letter :', letter)
  
var = 10                    # Second Example
while var > 0:              
   print('Current variable value :', var)
   var = var -1
   if var == 5:
      break
print("Good bye!")

Current Letter : P
Current Letter : y
Current Letter : t
Current variable value : 10
Current variable value : 9
Current variable value : 8
Current variable value : 7
Current variable value : 6
Good bye!


In [13]:
##input
##array avg marks
import numpy as np
marks = np.array([[10,30,40],[50,60,70],[80,90,95]])
avg_marks = np.average(marks,axis=0)
print  (avg_marks)
for x in avg_marks:
  #print(x)
  if x <=35:
    print ("Sorry! you only secured marks and failed. Pls try again")
  elif x > 35 and x <=65:
    print ("You passed with marks and got a passing grade")
  elif x > 65 and x <= 75:
    print ("you passed in First class")
  else: 
    print ("You rock - First Class with Distinction")
    

[46.66666667 60.         68.33333333]
You passed with marks and got a passing grade
You passed with marks and got a passing grade
you passed in First class


In [22]:
##input
##for continue we use
for letter in 'Python':     # First Example
   if letter == 'h':
      continue
   print('Current Letter :', letter)
  
var = 10                    # Second Example
while var > 0:              
   print('Current variable value :', var)
   var = var -1
   if var == 5:
      continue
print("Good bye!")

Current Letter : P
Current Letter : y
Current Letter : t
Current Letter : o
Current Letter : n
Current variable value : 10
Current variable value : 9
Current variable value : 8
Current variable value : 7
Current variable value : 6
Current variable value : 5
Current variable value : 4
Current variable value : 3
Current variable value : 2
Current variable value : 1
Good bye!


round(73.675,2) this function can be used for round off
ceil is also available 

In [23]:
##input
##ceil and round questions
import numpy as np
marks = [70,80,65,76,86.42]
print(marks)
print(np.average(marks))
avg = np.average(marks)
print(avg)
print(np.ceil(avg))
print(np.round(avg,2))
if avg > 80:
  print("A grade")
elif avg < 80 and avg > 60 :
  print("B grade")
elif avg < 60 and avg > 50:
  print("C grade")
  

[70, 80, 65, 76, 86.42]
75.48400000000001
75.48400000000001
76.0
75.48
B grade


In [24]:
##input
##advance stage
import numpy as np
marks = np.array([[10,10,10],[50,60,70],[70,75,65],[80,90,95]])
print (marks)
avg_marks = np.average(marks,axis=1)
print  (avg_marks)
for x in avg_marks:
  #print(x)
  if x <= 35:
    print ("Sorry! you only secured %0.2f marks and failed. Pls try again" % round(x,2))
  elif x > 35 and x <=65:
    print ("You passed with %0.2f marks and got a passing grade" % round(x,2))
  elif x > 65 and x <= 75:
    print ("you passed with %0.2f in First class" % x)
  else: 
    print ("You rock with %0.2f marks - First Class with Distinction" % x)

[[10 10 10]
 [50 60 70]
 [70 75 65]
 [80 90 95]]
[10.         60.         70.         88.33333333]
Sorry! you only secured 10.00 marks and failed. Pls try again
You passed with 60.00 marks and got a passing grade
you passed with 70.00 in First class
You rock with 88.33 marks - First Class with Distinction


Lambda example
refer to functions as variables
from Satheesh Kumar to everyone:
single line condinition
from Shaunak to everyone:
pass functions as parameters to other functions

In [25]:
#map is function ...and u want to map it to dataset
##input
##Lamda function
##for fast execution
##memory is in catch memory
##dynamic it is ,,all the work get done in only dataset x only
##instead recursive function calling again again....then lot of memory consume in iteration
L = [1,2,3,4]
x1 = list(map(lambda x: x**2, L))
print(x1)

[1, 4, 9, 16]


In [26]:
##input
##long way of square
L = [1, 2, 3, 4]
L1 = []
for x in L:
  L1.append(x**2)
print(L1)

[1, 4, 9, 16]


In [27]:
##input
##Lamda code practice
def myfunc(n):
  return lambda a : a * n
mydoubler = myfunc(2)
print(mydoubler(12))

24


In [28]:
##Input
def myfunc(n,a):
  return  a * n
mydoubler = myfunc(2,12)
print(mydoubler)

24


In [29]:
##lambda as well
def myfunc(n):
  return lambda a : a * n
mytripler = myfunc(3)
print(mytripler(11))

33


In [30]:
##input
##even odd with filter
##filter will return always true values
##returning true basic functionality
def even_fn(x):
  if x % 2 == 0:
    return True
  return False
print(list(filter(even_fn, [1, 3, 2, 5, 20, 21])))

[2, 20]


In [35]:
##lambda and filter use
#input
##error in lambda code
li = [1,23,45,30,22,56]
final_list = list(filter(lambda x: (x%2 != 0) , li)) 
#final_list = list(filter(lambda x: x%2 != 0 , li))
print(final_list)

SyntaxError: ignored

In [36]:
##lambda and filter use
#input
li = [1,23,45,30,22,56]
#final_list = list(filter(lambda x: (x%2 != 0) , li)) 
final_list = list(filter(lambda x: x%2 != 0 , li))
print(final_list)

[1, 23, 45]


In [34]:
##input
##Lambda
##primary numbers in python---might be
nums = range(2, 100)
#for i in nums:
  #print(i)
for i in range(2, 10):
  nums = list(filter(lambda x: x == i or x % i, nums))
print(nums)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [37]:
##input
##adding three numbers using lambda
x = lambda a, b, c : a + b + c
print(x(5, 6, 2))

13
