<a href="https://colab.research.google.com/github/MAHARAJASINGH/PythonBeginner/blob/master/PythonDay6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
##left little bit
##input
# python code to demonstrate summation  
# using reduce() and accumulate() 
  
# importing itertools for accumulate() 
import itertools 
  
# importing functools for reduce() 
import functools 
  
# initializing list  
lis = [ 1, 3, 4, 10, 4 ] 
  
# priting summation using accumulate() 
print ("The summation of list using accumulate is :",end="") 
print (list(itertools.accumulate(lis,lambda x,y : x+y)))
##print (list(itertools.accumulate(lambda x,y : x+y,lis))) 
  
# priting summation using reduce() 
print ("The summation of list using reduce is :",end="") 
print (functools.reduce(lambda x,y:x+y,lis))

The summation of list using accumulate is :[1, 4, 8, 18, 22]
The summation of list using reduce is :22


In [2]:
##use of code as well
a = [[1, 2, 3, 4], [5, 6], [7, 8, 9]]
for row in a:
    for elem in row:
        print(elem, end=' ')
    print() ##for blnk row it can be
    ##when we don't know the length of arry then we use range function
    

1 2 3 4 
5 6 
7 8 9 


In [3]:
##input
a = [[1, 2, 3, 4], [5, 6,7,8], [7, 8, 9,10],[1,2,3]]
for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i][j], end=' ')
    print()

1 2 3 4 
5 6 7 8 
7 8 9 10 
1 2 3 


In [4]:
##input
print(a)
for row in a:
    print(' '.join([str(elem) for elem in row]))

[[1, 2, 3, 4], [5, 6, 7, 8], [7, 8, 9, 10], [1, 2, 3]]
1 2 3 4
5 6 7 8
7 8 9 10
1 2 3


In [5]:
##input
a = [[1, 2, 3, 4], [5, 6,7,8], [7, 8, 9,10],[1,2,3]]
for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i][j], end=' ')
    print()

1 2 3 4 
5 6 7 8 
7 8 9 10 
1 2 3 


In [6]:
##input
a = [[1, 2, 3, 4], [5, 6], [7, 8, 9]]
s = 0
for row in a:
    for elem in row:
        s += elem
print(s)

45


In [7]:
##input
#working with arrays
a = [[1,2,3],[4,5,6]]
print(a[0])
print(a[1][2])
b=a[1]
print(b)
a[0][2]=7
print(a)
b[2]=9
print(b)
print(len(a))

[1, 2, 3]
6
[4, 5, 6]
[[1, 2, 7], [4, 5, 6]]
[4, 5, 9]
2


In [8]:
##input
#Iteration through list
print(a)
for row in a:
    print('$'.join([str(elem) for elem in row]))
    ##join means concat two elements with the character
    ##

[[1, 2, 7], [4, 5, 9]]
1$2$7
4$5$9


In [13]:
print(a)

[[1, 0, 0, 0], [2, 1, 0, 0], [2, 2, 1, 0], [2, 2, 2, 1]]


In [18]:
print(b)
print(a)
#print(c)
#print(d)

[4, 5, 9]
[[1, 0, 0, 0], [2, 1, 0, 0], [2, 2, 1, 0], [2, 2, 2, 1]]


In [12]:
##input
##flow with the join
n = 4
a = [[0] * n for i in range(n)]
for i in range(n):
    for j in range(n):
        if i < j:
            a[i][j] = 0
        elif i > j:
            a[i][j] = 2
        else:
            a[i][j] = 1
for row in a:
    print(' '.join([str(elem) for elem in row]))

for row in a:
  for elem in row:
    print(' '.join(str(elem)))
print ('xx'.join('yy'))

1 0 0 0
2 1 0 0
2 2 1 0
2 2 2 1
1
0
0
0
2
1
0
0
2
2
1
0
2
2
2
1
yxxy


THis prints lists with a variable number of nested lists
from Shaunak Guha Thakurata (internal) to everyone:
a = [[1, 2, 3, 4], [5, 6], [7, 8, 9,[10,11,12]]]
def sumlist(listToSum):
  return reduce(lambda x,y:(sumlist(x) if isinstance(x,list) else x)+(sumlist(y) if isinstance(y,list) else y),listToSum)
print(sumlist(a))
from Shaunak Guha Thakurata (internal) to everyone:
No nest loops. Used recursion and lambda instead

In [19]:
##input
##dynamic creation of array

for i in range(7):print(i) 
[[1 for j in range(4)] for i in range(7)]

0
1
2
3
4
5
6


[[1, 1, 1, 1],
 [1, 1, 1, 1],
 [1, 1, 1, 1],
 [1, 1, 1, 1],
 [1, 1, 1, 1],
 [1, 1, 1, 1],
 [1, 1, 1, 1]]

In [20]:
##input
[[i * j for j in range(4)] for i in range(3)]

[[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 4, 6]]

In [21]:
##input
[[i + j for j in range(4)] for i in range(3)]

[[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5]]

In [22]:
##input
[[i + j for j in range(4)] for i in range(3)]

[[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5]]

In [23]:
##input
print(a)
for i in range(0, 4):
  for j in range(0,4):
    print(a[i][j])
    ##single dimensional array
    ##you're right ... a=range(4) is a single dimensional array

[[1, 0, 0, 0], [2, 1, 0, 0], [2, 2, 1, 0], [2, 2, 2, 1]]
1
0
0
0
2
1
0
0
2
2
1
0
2
2
2
1


In [24]:
##input
print(n)
for i in range(n):
    for j in range(n):
        if i < j:
            a[i][j] = 0
        elif i > j:
            a[i][j] = 2
        else:
            a[i][j] = 1
print(a)
for i in range(0, 4):
  for j in range(0,4):
    print(a[i][j])

print(a)

4
[[1, 0, 0, 0], [2, 1, 0, 0], [2, 2, 1, 0], [2, 2, 2, 1]]
1
0
0
0
2
1
0
0
2
2
1
0
2
2
2
1
[[1, 0, 0, 0], [2, 1, 0, 0], [2, 2, 1, 0], [2, 2, 2, 1]]


In [25]:
print(n)

4


In [ ]:
###numpy.zeros(16).reshape(4,4)

In [30]:
##input slicing example
#array slicing
##it appears like ... starting from [2]nd element upto the [7]th, get every 2nd element 
##the 3 parameters are start, end and how you want to slice
###array slicing
import numpy as np
a = np.arange(10)
print(a)
s = slice(2,7,2) # First parameter is lower index, second is the upper index, 3rd parameter is how many slicing
print(a[s])
import numpy as np 
a = np.arange(10) 
print(a)
s = slice(2,7,2) 
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [31]:

import numpy as np 
a = np.arange(10) 
print(a)
print(a[2:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [32]:
##input
for i in range(n):
    for j in range(n):
        if i < j:
            a[i][j] = 0
        elif i > j:
            a[i][j] = 2
        else:
            a[i][j] = 1

TypeError: ignored

#7/8/2020 take a list of student marks, create a parent mark, create 3 lists using filter conditions using a criteria of above 80, above 60, below 40
Use reduce and create a grade for each list/student

In [34]:
##input
n=4
a = [[0] * n for i in range(n)] 