<a href="https://colab.research.google.com/github/MAHARAJASINGH/PythonBeginner/blob/master/PythonDay14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
##input
##something abt pivot table
##dataframe 
##binnng  and melting and exploding the dataframe
##mean ,,,median,,,normal distribution also
##data foundations statistical techniques
#group by mean
import pandas as pd
import numpy as np
 
data = {'Product':['Box','Bottles','Pen','Markers','Bottles','Pen','Markers','Bottles','Box','Markers','Markers','Pen'],
       'State':['Alaska','California','Texas','North Carolina','California','Texas','Alaska','Texas','North Carolina','Alaska','California','Texas'],
       'Sales':[14,24,31,12,13,7,9,31,18,16,18,14]}
 
df1=pd.DataFrame(data, columns=['Product','State','Sales'])
 
print(df1)
gk=df1.groupby(['State','Product'])['Sales']
print(gk.first())
print(df1.groupby(['State','Product'])['Sales'].mean())
#from Sharada Lakshmanan (internal) to everyone:
#df1.groupby(['State','Product'],as_index = False).sum().pivot('State','Product').fillna(0)


    Product           State  Sales
0       Box          Alaska     14
1   Bottles      California     24
2       Pen           Texas     31
3   Markers  North Carolina     12
4   Bottles      California     13
5       Pen           Texas      7
6   Markers          Alaska      9
7   Bottles           Texas     31
8       Box  North Carolina     18
9   Markers          Alaska     16
10  Markers      California     18
11      Pen           Texas     14
State           Product
Alaska          Box        14
                Markers     9
California      Bottles    24
                Markers    18
North Carolina  Box        18
                Markers    12
Texas           Bottles    31
                Pen        31
Name: Sales, dtype: int64
State           Product
Alaska          Box        14.000000
                Markers    12.500000
California      Bottles    18.500000
                Markers    18.000000
North Carolina  Box        18.000000
                Markers    12.000000
Texas    

from Sharada Lakshmanan (internal) to everyone:
df1.groupby(['State','Product'],as_index = False).sum().pivot('State','Product').fillna(0)

In [4]:
##binning in the dataset
##intervalling in the dataframe and the dataset
##load the dataset
##print the dataset
##need linear models as well
##in binning take the upper limit and lower limint and mid value is median
import numpy as np   
import math 
from sklearn.datasets import load_iris 
from sklearn import datasets, linear_model, metrics  
#load iris data set  
#from sklearn import datasets, linear_model, metrics  
# load iris data set 
dataset = load_iris()    
a = dataset.data 
b = np.zeros(150) 
  
# take 1st column among 4 column of data set  
for i in range (150): 
    b[i]=a[i,1]    
  
b=np.sort(b)  #sort the array 
  
# create bins 
bin1=np.zeros((30,5))  
bin2=np.zeros((30,5)) 
bin3=np.zeros((30,5)) 
  
# Bin mean 
for i in range (0,150,5): 
    k=int(i/5) 
    mean=(b[i] + b[i+1] + b[i+2] + b[i+3] + b[i+4])/5
    for j in range(5): 
        bin1[k,j]=mean 
print("Bin Mean: \n",bin1) 
     
# Bin boundaries 
for i in range (0,150,5): 
    k=int(i/5) 
    for j in range (5): 
        if (b[i+j]-b[i]) < (b[i+4]-b[i+j]): 
            bin2[k,j]=b[i] 
        else: 
            bin2[k,j]=b[i+4]        
print("Bin Boundaries: \n",bin2) 
  
# Bin median 
for i in range (0,150,5): 
    k=int(i/5) 
    for j in range (5): 
        bin3[k,j]=b[i+2] 
print("Bin Median: \n",bin3)

Bin Mean: 
 [[2.18 2.18 2.18 2.18 2.18]
 [2.34 2.34 2.34 2.34 2.34]
 [2.48 2.48 2.48 2.48 2.48]
 [2.52 2.52 2.52 2.52 2.52]
 [2.62 2.62 2.62 2.62 2.62]
 [2.7  2.7  2.7  2.7  2.7 ]
 [2.74 2.74 2.74 2.74 2.74]
 [2.8  2.8  2.8  2.8  2.8 ]
 [2.8  2.8  2.8  2.8  2.8 ]
 [2.86 2.86 2.86 2.86 2.86]
 [2.9  2.9  2.9  2.9  2.9 ]
 [2.96 2.96 2.96 2.96 2.96]
 [3.   3.   3.   3.   3.  ]
 [3.   3.   3.   3.   3.  ]
 [3.   3.   3.   3.   3.  ]
 [3.   3.   3.   3.   3.  ]
 [3.04 3.04 3.04 3.04 3.04]
 [3.1  3.1  3.1  3.1  3.1 ]
 [3.12 3.12 3.12 3.12 3.12]
 [3.2  3.2  3.2  3.2  3.2 ]
 [3.2  3.2  3.2  3.2  3.2 ]
 [3.26 3.26 3.26 3.26 3.26]
 [3.34 3.34 3.34 3.34 3.34]
 [3.4  3.4  3.4  3.4  3.4 ]
 [3.4  3.4  3.4  3.4  3.4 ]
 [3.5  3.5  3.5  3.5  3.5 ]
 [3.58 3.58 3.58 3.58 3.58]
 [3.74 3.74 3.74 3.74 3.74]
 [3.82 3.82 3.82 3.82 3.82]
 [4.12 4.12 4.12 4.12 4.12]]
Bin Boundaries: 
 [[2.  2.3 2.3 2.3 2.3]
 [2.3 2.3 2.3 2.4 2.4]
 [2.4 2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5 2.6]
 [2.6 2.6 2.6 2.6 2.7]
 [2.7 2.7 2.7 

In [6]:
##input
import numpy as np   
import math 
from sklearn.datasets import load_iris 
from sklearn import datasets, linear_model, metrics  
# load iris data set 
dataset = load_iris()    
a = dataset.data 
b = np.zeros(150) 
  
# take 1st column among 4 column of data set  
for i in range (150): 
    b[i]=a[i,1]    
  
b=np.sort(b)  #sort the array 
  
# create bins 
bin1=np.zeros((30,5))  
bin2=np.zeros((30,5)) 
bin3=np.zeros((30,5)) 

In [7]:
# Bin mean 
for i in range (0,150,5): 
    k=int(i/5) 
    mean=(b[i] + b[i+1] + b[i+2] + b[i+3] + b[i+4])/5
    for j in range(5): 
        bin1[k,j]=mean 
print("Bin Mean: \n",bin1) 

Bin Mean: 
 [[2.18 2.18 2.18 2.18 2.18]
 [2.34 2.34 2.34 2.34 2.34]
 [2.48 2.48 2.48 2.48 2.48]
 [2.52 2.52 2.52 2.52 2.52]
 [2.62 2.62 2.62 2.62 2.62]
 [2.7  2.7  2.7  2.7  2.7 ]
 [2.74 2.74 2.74 2.74 2.74]
 [2.8  2.8  2.8  2.8  2.8 ]
 [2.8  2.8  2.8  2.8  2.8 ]
 [2.86 2.86 2.86 2.86 2.86]
 [2.9  2.9  2.9  2.9  2.9 ]
 [2.96 2.96 2.96 2.96 2.96]
 [3.   3.   3.   3.   3.  ]
 [3.   3.   3.   3.   3.  ]
 [3.   3.   3.   3.   3.  ]
 [3.   3.   3.   3.   3.  ]
 [3.04 3.04 3.04 3.04 3.04]
 [3.1  3.1  3.1  3.1  3.1 ]
 [3.12 3.12 3.12 3.12 3.12]
 [3.2  3.2  3.2  3.2  3.2 ]
 [3.2  3.2  3.2  3.2  3.2 ]
 [3.26 3.26 3.26 3.26 3.26]
 [3.34 3.34 3.34 3.34 3.34]
 [3.4  3.4  3.4  3.4  3.4 ]
 [3.4  3.4  3.4  3.4  3.4 ]
 [3.5  3.5  3.5  3.5  3.5 ]
 [3.58 3.58 3.58 3.58 3.58]
 [3.74 3.74 3.74 3.74 3.74]
 [3.82 3.82 3.82 3.82 3.82]
 [4.12 4.12 4.12 4.12 4.12]]


In [8]:
##input
# Bin boundaries 
for i in range (0,150,5): 
    k=int(i/5) 
    for j in range (5): 
        if (b[i+j]-b[i]) < (b[i+4]-b[i+j]): 
            bin2[k,j]=b[i] 
        else: 
            bin2[k,j]=b[i+4]        
print("Bin Boundaries: \n",bin2) 

Bin Boundaries: 
 [[2.  2.3 2.3 2.3 2.3]
 [2.3 2.3 2.3 2.4 2.4]
 [2.4 2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5 2.6]
 [2.6 2.6 2.6 2.6 2.7]
 [2.7 2.7 2.7 2.7 2.7]
 [2.7 2.7 2.7 2.8 2.8]
 [2.8 2.8 2.8 2.8 2.8]
 [2.8 2.8 2.8 2.8 2.8]
 [2.8 2.8 2.9 2.9 2.9]
 [2.9 2.9 2.9 2.9 2.9]
 [2.9 2.9 3.  3.  3. ]
 [3.  3.  3.  3.  3. ]
 [3.  3.  3.  3.  3. ]
 [3.  3.  3.  3.  3. ]
 [3.  3.  3.  3.  3. ]
 [3.  3.  3.  3.1 3.1]
 [3.1 3.1 3.1 3.1 3.1]
 [3.1 3.1 3.1 3.1 3.2]
 [3.2 3.2 3.2 3.2 3.2]
 [3.2 3.2 3.2 3.2 3.2]
 [3.2 3.2 3.3 3.3 3.3]
 [3.3 3.3 3.3 3.4 3.4]
 [3.4 3.4 3.4 3.4 3.4]
 [3.4 3.4 3.4 3.4 3.4]
 [3.5 3.5 3.5 3.5 3.5]
 [3.5 3.6 3.6 3.6 3.6]
 [3.7 3.7 3.7 3.8 3.8]
 [3.8 3.8 3.8 3.8 3.9]
 [3.9 3.9 3.9 4.4 4.4]]


In [9]:
##input
# Bin median 
for i in range (0,150,5): 
    k=int(i/5) 
    for j in range (5): 
        bin3[k,j]=b[i+2] 
print("Bin Median: \n",bin3) 

Bin Median: 
 [[2.2 2.2 2.2 2.2 2.2]
 [2.3 2.3 2.3 2.3 2.3]
 [2.5 2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5 2.5]
 [2.6 2.6 2.6 2.6 2.6]
 [2.7 2.7 2.7 2.7 2.7]
 [2.7 2.7 2.7 2.7 2.7]
 [2.8 2.8 2.8 2.8 2.8]
 [2.8 2.8 2.8 2.8 2.8]
 [2.9 2.9 2.9 2.9 2.9]
 [2.9 2.9 2.9 2.9 2.9]
 [3.  3.  3.  3.  3. ]
 [3.  3.  3.  3.  3. ]
 [3.  3.  3.  3.  3. ]
 [3.  3.  3.  3.  3. ]
 [3.  3.  3.  3.  3. ]
 [3.  3.  3.  3.  3. ]
 [3.1 3.1 3.1 3.1 3.1]
 [3.1 3.1 3.1 3.1 3.1]
 [3.2 3.2 3.2 3.2 3.2]
 [3.2 3.2 3.2 3.2 3.2]
 [3.3 3.3 3.3 3.3 3.3]
 [3.3 3.3 3.3 3.3 3.3]
 [3.4 3.4 3.4 3.4 3.4]
 [3.4 3.4 3.4 3.4 3.4]
 [3.5 3.5 3.5 3.5 3.5]
 [3.6 3.6 3.6 3.6 3.6]
 [3.7 3.7 3.7 3.7 3.7]
 [3.8 3.8 3.8 3.8 3.8]
 [4.1 4.1 4.1 4.1 4.1]]


In [10]:
##input
#get the count of missing values
###binning the data
import pandas as pd
import numpy as np
 
#Create a DataFrame
df1 = {
    'Name':['George','Andrea','micheal','maggie','Ravi','Xien','Jalpa',np.nan],
    'State':['Arizona','Georgia','Newyork','Indiana','Florida','California',np.nan,np.nan],
    'Gender':["M","F","M","F","M","M",np.nan,np.nan],      
    'Score':[63,48,56,75,np.nan,77,np.nan,np.nan]
     
   }
 
df1 = pd.DataFrame(df1,columns=['Name','State','Gender','Score'])
print(df1)
df1.isnull().sum()

      Name       State Gender  Score
0   George     Arizona      M   63.0
1   Andrea     Georgia      F   48.0
2  micheal     Newyork      M   56.0
3   maggie     Indiana      F   75.0
4     Ravi     Florida      M    NaN
5     Xien  California      M   77.0
6    Jalpa         NaN    NaN    NaN
7      NaN         NaN    NaN    NaN


Name      1
State     2
Gender    2
Score     3
dtype: int64

In [11]:
##input
df_ages = pd.DataFrame({'age': np.random.randint(21, 51, 8)})
print(df_ages)
df_ages['age_bins'] = pd.cut(x=df_ages['age'], bins=[20, 29, 39, 49])
print(df_ages)
print(df_ages['age_bins'].unique())

   age
0   50
1   42
2   35
3   31
4   42
5   31
6   26
7   32
   age      age_bins
0   50           NaN
1   42  (39.0, 49.0]
2   35  (29.0, 39.0]
3   31  (29.0, 39.0]
4   42  (39.0, 49.0]
5   31  (29.0, 39.0]
6   26  (20.0, 29.0]
7   32  (29.0, 39.0]
[NaN, (39.0, 49.0], (29.0, 39.0], (20.0, 29.0]]
Categories (3, interval[int64]): [(20, 29] < (29, 39] < (39, 49]]


In [12]:
##input
df_ages['age_by_decade'] = pd.cut(x=df_ages['age'], bins=[20, 29, 39, 49], labels=['20s', '30s', '40s'])
print(df_ages)

   age      age_bins age_by_decade
0   50           NaN           NaN
1   42  (39.0, 49.0]           40s
2   35  (29.0, 39.0]           30s
3   31  (29.0, 39.0]           30s
4   42  (39.0, 49.0]           40s
5   31  (29.0, 39.0]           30s
6   26  (20.0, 29.0]           20s
7   32  (29.0, 39.0]           30s


In [13]:
##How do i find the sum of elements in each bin?
##df_ages.groupby(['age_by_decade']).count()
#discretize it or bin it or categorize it based on the values of the variable. For example, let us say you have measurements of height and want to discretize it such that it is 0 or 1 depending on if the height is below or above a certain value of height.
# load numpy
import numpy as np
# load pandas
import pandas as pd
# set a random seed to reproduce
np.random.seed(123)
# create 10 random integers  
x = np.random.randint(low=25, high=200, size=10)
x = np.sort(x)
print(x)
#where we use 50 as threshold to bin our data into two categories. One with values less than 50 are in the 0 category and the ones above 50 are in the 1 category.
np.digitize(x,bins=[50])

[ 42  82  91 108 121 123 131 134 148 151]


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
##input
##np.digitize(x,[50,100])
df = pd.DataFrame({"height":x})    
df['binned']=pd.cut(x=df['height'], bins=[0,25,50,100,200])
print(df)

   height      binned
0      42    (25, 50]
1      82   (50, 100]
2      91   (50, 100]
3     108  (100, 200]
4     121  (100, 200]
5     123  (100, 200]
6     131  (100, 200]
7     134  (100, 200]
8     148  (100, 200]
9     151  (100, 200]


In [15]:
##input
df['height_bin']=pd.cut(x=df['height'], bins=[0,25,50,100,200], 
                        labels=["very short", " short", "medium","tall"])
print(df.head())

   height      binned height_bin
0      42    (25, 50]      short
1      82   (50, 100]     medium
2      91   (50, 100]     medium
3     108  (100, 200]       tall
4     121  (100, 200]       tall


In [16]:
##input
import pandas as pd
import numpy as np
 
#Create a DataFrame
df1 = {
    'Name':['George','Andrea','micheal','maggie','Ravi','Xien','Jalpa','Tyieren'],    
    'Score':[63,48,56,75,32,77,85,22]
     
   }
 
 
df1 = pd.DataFrame(df1,columns=['Name','Score'])
print(df1)
''' binning or bucketing with range'''
 
bins = [0, 25, 50, 75, 100]
df1['binned'] = pd.cut(df1['Score'], bins)
print (df1)

      Name  Score
0   George     63
1   Andrea     48
2  micheal     56
3   maggie     75
4     Ravi     32
5     Xien     77
6    Jalpa     85
7  Tyieren     22
      Name  Score     binned
0   George     63   (50, 75]
1   Andrea     48   (25, 50]
2  micheal     56   (50, 75]
3   maggie     75   (50, 75]
4     Ravi     32   (25, 50]
5     Xien     77  (75, 100]
6    Jalpa     85  (75, 100]
7  Tyieren     22    (0, 25]


In [17]:
##input
import pandas as pd
import numpy as np
 
#Create a DataFrame
df1 = {
    'Name':['George','Andrea','micheal','maggie','Ravi','Xien','Jalpa','Tyieren'],    
    'Score':[63,48,56,75,32,77,85,22]
     
   }
 
 
df1 = pd.DataFrame(df1,columns=['Name','Score'])
print(df1)
''' binning or bucketing with range'''
 
bins = [0, 25, 50, 75, 100]
df1['binned'] = pd.cut(df1['Score'], bins)
print (df1)
##melting and not melting of the data frame


      Name  Score
0   George     63
1   Andrea     48
2  micheal     56
3   maggie     75
4     Ravi     32
5     Xien     77
6    Jalpa     85
7  Tyieren     22
      Name  Score     binned
0   George     63   (50, 75]
1   Andrea     48   (25, 50]
2  micheal     56   (50, 75]
3   maggie     75   (50, 75]
4     Ravi     32   (25, 50]
5     Xien     77  (75, 100]
6    Jalpa     85  (75, 100]
7  Tyieren     22    (0, 25]


In [18]:
##input
import pandas as pd
import numpy as np
 
#Create a DataFrame
df1 = {
    'Name':['George','Andrea','micheal','maggie','Ravi','Xien','Jalpa','Tyieren'],    
    'Score':[63,48,56,75,32,77,85,22]
     
   }
 
 
df1 = pd.DataFrame(df1,columns=['Name','Score'])
print(df1)
''' binning or bucketing with range'''
 
bins = [0, 25, 50, 75, 100]
df1['binned'] = pd.cut(df1['Score'], bins)
print (df1)

      Name  Score
0   George     63
1   Andrea     48
2  micheal     56
3   maggie     75
4     Ravi     32
5     Xien     77
6    Jalpa     85
7  Tyieren     22
      Name  Score     binned
0   George     63   (50, 75]
1   Andrea     48   (25, 50]
2  micheal     56   (50, 75]
3   maggie     75   (50, 75]
4     Ravi     32   (25, 50]
5     Xien     77  (75, 100]
6    Jalpa     85  (75, 100]
7  Tyieren     22    (0, 25]


In [19]:
##input
import pandas as pd
import numpy as np
 
df1 = {
    'State':['Arizona AZ','Georgia GG','Newyork NY','Indiana IN','Florida FL']}
 
df1 = pd.DataFrame(df1,columns=['State'])
print(df1)
print(df1.State.str.split().tolist())
df2 = pd.DataFrame(df1.State.str.split().tolist(), columns="State State_code".split())
print(df2)

        State
0  Arizona AZ
1  Georgia GG
2  Newyork NY
3  Indiana IN
4  Florida FL
[['Arizona', 'AZ'], ['Georgia', 'GG'], ['Newyork', 'NY'], ['Indiana', 'IN'], ['Florida', 'FL']]
     State State_code
0  Arizona         AZ
1  Georgia         GG
2  Newyork         NY
3  Indiana         IN
4  Florida         FL


Instead of splitting columns, i can straight away give columns=('State', 'State_code'

In [20]:
##input
##reshape and melt is almost equivalent
import pandas as pd
import numpy as np
 
df1 = {
    'State':['Arizona AZ','Georgia GG','Newyork NY','Indiana IN','Florida FL']}
 
df1 = pd.DataFrame(df1,columns=['State'])
print(df1)
print(df1.State.str.split().tolist())
df2 = pd.DataFrame(df1.State.str.split().tolist(), columns="State State_code".split())
print(df2)

        State
0  Arizona AZ
1  Georgia GG
2  Newyork NY
3  Indiana IN
4  Florida FL
[['Arizona', 'AZ'], ['Georgia', 'GG'], ['Newyork', 'NY'], ['Indiana', 'IN'], ['Florida', 'FL']]
     State State_code
0  Arizona         AZ
1  Georgia         GG
2  Newyork         NY
3  Indiana         IN
4  Florida         FL


from Satheesh Kumar to everyone:
yes working
from Edwin Herald Ponniah (internal) to everyone:
Can we split based on any stringtokenizer?
from Sandeep Kumar (internal) to everyone:
i tried with three data in the same state, state_code and Zip code.... it is notworking
from Sandeep Kumar (internal) to everyone:
can we take a look
from Sandeep Kumar (internal) to everyone:
it worked
from Sandeep Kumar (internal) to everyone:
i was doing mistake

In [21]:
##input
df3 = {
    'State':['Arizona AZ 89034','Georgia GG 34582','Newyork NY 01232','Indiana IN 20987','Florida  09873']}
 
df3 = pd.DataFrame(df3,columns=['State'])
print(df3)
print(df3.State.str.split().tolist())
df4 = pd.DataFrame(df3.State.str.split().tolist(), columns="State State_code ZipCode".split())
print(df4)

              State
0  Arizona AZ 89034
1  Georgia GG 34582
2  Newyork NY 01232
3  Indiana IN 20987
4    Florida  09873
[['Arizona', 'AZ', '89034'], ['Georgia', 'GG', '34582'], ['Newyork', 'NY', '01232'], ['Indiana', 'IN', '20987'], ['Florida', '09873']]
     State State_code ZipCode
0  Arizona         AZ   89034
1  Georgia         GG   34582
2  Newyork         NY   01232
3  Indiana         IN   20987
4  Florida      09873    None


from Sandeep Kumar (internal) to everyone:
Thats okay i got it
from Satheesh Kumar to everyone:
specify column name
from Vijay Rajagopalan (internal) to everyone:
Florida needs FL
from Joseph Cutler (internal) to everyone:
that is deliberate error .. Sandeep wants us to work on it
from Sandeep Kumar (internal) to everyone:
yes i  wanted to check with data missing whats happening
from Sandeep Kumar (internal) to everyone:
in the earlier case it was taking none when the second parameter was not provided

In [22]:
##input
def word_count(str):
    counts = dict()
    words = str.split()
    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1
    return counts
3
print( word_count('the quick brown fox jumps over the lazy dog.'))

{'the': 2, 'quick': 1, 'brown': 1, 'fox': 1, 'jumps': 1, 'over': 1, 'lazy': 1, 'dog.': 1}


from Sandeep Kumar (internal) to everyone:
but when three values are passed then its not able to find the second element missing eventhough i gave two spaces between Florida and zip code
from Joseph Cutler (internal) to everyone:
it will work if we use other delimeter and specify it in the split function
from Joseph Cutler (internal) to everyone:
the default argument is a whitespace
from Ashutosh to everyone:
columns="State,State_code".split(",")

In [23]:
##input
def word_count(str):
    counts = dict()
    words = str.split()
    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1
    return counts
3
print( word_count('the quick brown fox jumps over the lazy dog.'))

{'the': 2, 'quick': 1, 'brown': 1, 'fox': 1, 'jumps': 1, 'over': 1, 'lazy': 1, 'dog.': 1}


from Joseph Cutler (internal) to everyone:
worked with ',' as a delimeter
from Joseph Cutler (internal) to everyone:

In [24]:
##input
df3 = {
    'State':['Arizona,AZ,89034','Georgia,GG,34582','Newyork,NY,01232','Indiana,IN,20987','Florida,,09873']}
 
df3 = pd.DataFrame(df3,columns=['State'])
print(df3)
print(df3.State.str.split(',').tolist())
df4 = pd.DataFrame(df3.State.str.split(',').tolist(), columns="State State_code ZipCode".split())
print(df4)

              State
0  Arizona,AZ,89034
1  Georgia,GG,34582
2  Newyork,NY,01232
3  Indiana,IN,20987
4    Florida,,09873
[['Arizona', 'AZ', '89034'], ['Georgia', 'GG', '34582'], ['Newyork', 'NY', '01232'], ['Indiana', 'IN', '20987'], ['Florida', '', '09873']]
     State State_code ZipCode
0  Arizona         AZ   89034
1  Georgia         GG   34582
2  Newyork         NY   01232
3  Indiana         IN   20987
4  Florida              09873


from Joseph Cutler (internal) to everyone:
i think the problem is when we use the whitespaces.. there must be a way to work around it
from Sandeep Kumar (internal) to everyone:
Thanks Joeseph, yes thats correct
from Sandeep Kumar (internal) to everyone:
but in this State code is marked as blank , i mean no value is shown... i was expecting it to be NAN or none
from Vijay Rajagopalan (internal) to everyone:
1. Split has a separator as an optional parameter. Default is space

In [26]:
##input
#string replace in data frame
import pandas as pd
import numpy as np
 
#Create a DataFrame
df1 = {
    'State':['zona AZ','Georgia GG','Newyork NY','Indiana IN','Florida FL'],
   'Score':[62,47,55,74,31]}
 
df1 = pd.DataFrame(df1,columns=['State','Score'])
print(df1)
df1.replace(regex=['^.'],value='HE')
#from Vijay Rajagopalan (internal) to everyone:
#2. Split() returns list. so it would be "empty" list if no corresponding string value to return. (not NaN)

        State  Score
0     zona AZ     62
1  Georgia GG     47
2  Newyork NY     55
3  Indiana IN     74
4  Florida FL     31


State  Score
0     HEona AZ     62
1  HEeorgia GG     47
2  HEewyork NY     55
3  HEndiana IN     74
4  HElorida FL     31

In [27]:
##input
import pandas as pd
import numpy as np
 
#Create a DataFrame
df1 = {
    'State':['Arizona AZ','Georgia GG','Newyork NY','Indiana IN','Florida FL'],
   'Score':[62,47,55,74,31]}
 
df1 = pd.DataFrame(df1,columns=['State','Score'])
print(df1)
df1['State_reverse'] = df1.loc[:,'State'].apply(lambda x: x[::-1])
print(df1)

        State  Score
0  Arizona AZ     62
1  Georgia GG     47
2  Newyork NY     55
3  Indiana IN     74
4  Florida FL     31
        State  Score State_reverse
0  Arizona AZ     62    ZA anozirA
1  Georgia GG     47    GG aigroeG
2  Newyork NY     55    YN kroyweN
3  Indiana IN     74    NI anaidnI
4  Florida FL     31    LF adirolF


In [28]:
##input
df1 = {
    'State':['Arizona AZ','Georgia GG','Newyork NY','Indiana IN','Florida FL'],
   'Score':[62,47,55,74,31]}
 
df1 = pd.DataFrame(df1,columns=['State','Score'])
print(df1)
df1['State_reverse'] = df1.loc[:,'State'].apply(lambda x: x[::-1])
print(df1)

        State  Score
0  Arizona AZ     62
1  Georgia GG     47
2  Newyork NY     55
3  Indiana IN     74
4  Florida FL     31
        State  Score State_reverse
0  Arizona AZ     62    ZA anozirA
1  Georgia GG     47    GG aigroeG
2  Newyork NY     55    YN kroyweN
3  Indiana IN     74    NI anaidnI
4  Florida FL     31    LF adirolF


In [29]:
##input
df = pd.DataFrame({'P': {0: 'p', 1: 'q', 2: 'r'},
                   'Q': {0: 1, 1: 3, 2: 5},
                   'R': {0: 2, 1: 4, 2: 6}})
print(df)
df.melt(id_vars=['P'], value_vars=['Q'])

   P  Q  R
0  p  1  2
1  q  3  4
2  r  5  6


P variable  value
0  p        Q      1
1  q        Q      3
2  r        Q      5

from 493740 to everyone:
can you please explain melt again
from 493740 to everyone:
no sharda.. sorry.. i dont remember
from Edwin Herald Ponniah (internal) to everyone:
Shaunak, do you have any code to show?
from Edwin Herald Ponniah (internal) to everyone:
on that day you have shown
from yograj to everyone:
can not see the screen
from ManiKandan Lagichetty (internal) to everyone:
Sharada share the screen
from suresh thammiraju to everyone:
I am unable to hear
from yograj to everyone:
but reshape is the part of numpy. while melt for pandas, m i right?

In [30]:
##input
# importing pandas as pd 
import pandas as pd 
  
# creating a dataframe 
df = pd.DataFrame({'Name': {0: 'John', 1: 'Bob', 2: 'Shiela'}, 
                   'Course': {0: 'Masters', 1: 'Graduate', 2: 'Graduate'}, 
                   'Age': {0: 27, 1: 23, 2: 21}}) 
print(df )
# Name is id_vars and Course is value_vars 
pd.melt(df, id_vars =['Name'], value_vars =['Course'])
pd.melt(df, id_vars =['Name'], value_vars =['Age'])

     Name    Course  Age
0    John   Masters   27
1     Bob  Graduate   23
2  Shiela  Graduate   21


Name variable  value
0    John      Age     27
1     Bob      Age     23
2  Shiela      Age     21

explode is also there ....breakdown in 2 -3 lists

In [31]:
##input
df = pd.DataFrame({'P': [[2, 3, 4], 'fff', [], [4, 5]], 'Q': 2})
print(df)
df = pd.DataFrame({'P': [[2, 3, 4], 'fff', [], [4, 5]], 'Q': 2})
df.explode('P')

           P  Q
0  [2, 3, 4]  2
1        fff  2
2         []  2
3     [4, 5]  2


P  Q
0    2  2
0    3  2
0    4  2
1  fff  2
2  NaN  2
3    4  2
3    5  2